services:
  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    command:
      [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Str0ngP4ssw0rd
    ports:
      - "1433:1433"
  xtdb:
    image: ghcr.io/xtdb/xtdb:nightly
    pull_policy: always
    ports:
      - "5432:5432"
