version: 2
jobs:
  build:
    working_directory: ~/next-jdbc
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.442
#    environment:
#      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: next-jdbc-{{ checksum "deps.edn" }}
      - run: clojure -R:test:runner -Spath
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: next-jdbc-{{ checksum "deps.edn" }}
      - run: clojure -A:test:runner
