name: Release Version

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.1.1429'
      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Setup Databases
        run: docker-compose up -d
        env:
          MYSQL_ROOT_PASSWORD: testing
      - name: Run MariaDB Tests
        run: clojure -X:test
        env:
          MYSQL_ROOT_PASSWORD: testing
          NEXT_JDBC_TEST_MYSQL: yes
          NEXT_JDBC_TEST_MARIADB: yes
      - name: Run All Tests and Release
        run: clojure -T:build ci :snapshot false
        env:
          MYSQL_ROOT_PASSWORD: testing
          NEXT_JDBC_TEST_MYSQL: yes
          NEXT_JDBC_TEST_MSSQL: yes
          MSSQL_SA_PASSWORD: Str0ngP4ssw0rd
      - name: Deploy Release
        run: clojure -T:build deploy :snapshot false
        env:
          CLOJARS_PASSWORD: ${{secrets.DEPLOY_TOKEN}}
          CLOJARS_USERNAME: ${{secrets.DEPLOY_USERNAME}}
