name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '14', '15', '16', '17-ea' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.933'
      - name: Run Tests
        run: clojure -T:build ci

  build-graalvm-old:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graalvm: [ '19.3.6', '20.3.2' ]
        base: [ 'java8', 'java11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: ${{ matrix.graalvm }}
          java: ${{ matrix.base }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.933'
      - name: Run Tests
        run: clojure -T:build ci

  build-graalvm-new:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graalvm: [ '21.1.0' ]
        base: [ 'java11', 'java16' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: ${{ matrix.graalvm }}
          java: ${{ matrix.base }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.3.933'
      - name: Run Tests
        run: clojure -T:build ci
