name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '16', '17', '18' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.11.1.1155'
      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Setup Databases
        run: docker-compose up -d
        env:
          MYSQL_ROOT_PASSWORD: testing
      - name: Run MariaDB Tests
        run: clojure -X:test
        env:
          MYSQL_ROOT_PASSWORD: testing
          NEXT_JDBC_TEST_MYSQL: yes
          NEXT_JDBC_TEST_MARIADB: yes
      - name: Run All Tests
        run: clojure -X:test
        env:
          MYSQL_ROOT_PASSWORD: testing
          NEXT_JDBC_TEST_MYSQL: yes
          NEXT_JDBC_TEST_MSSQL: yes
          MSSQL_SA_PASSWORD: Str0ngP4ssw0rd

  build-graalvm-new:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graalvm: [ '21.1.0' ]
        base: [ 'java11', 'java16' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: ${{ matrix.graalvm }}
          java: ${{ matrix.base }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.11.1.1155'
      - name: Cache All The Things
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Run Tests
        run: clojure -T:build test
